# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: cloud
name: common
version: 2.1.3
readme: README.md
authors:
- Ansible (https://github.com/ansible)
description: Set of common files for the cloud collections
license_file: LICENSE
tags:
- cloud
- virtualization
repository: https://github.com/ansible-collections/cloud.common
homepage: https://github.com/ansible-collections/cloud.common
issues: https://github.com/ansible-collections/cloud.common/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
