---
name: Unit tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - stable-*

jobs:
  unit-source:
    uses: ansible-network/github_actions/.github/workflows/unit_source.yml@main
    with:
        matrix_exclude: >-
          [
            {
              "ansible-version": "devel"
            },
            {
              "ansible-version": "milestone"
            },
            {
              "ansible-version": "stable-2.19"
            },
            {
              "ansible-version": "stable-2.18",
              "python-version": "3.10"
            },
            {
              "ansible-version": "stable-2.17",
              "python-version": "3.13"
            },
            {
              "ansible-version": "stable-2.16",
              "python-version": "3.12"
            },
            {
              "ansible-version": "stable-2.16",
              "python-version": "3.13"
            },
            {
              "ansible-version": "stable-2.15",
              "python-version": "3.12"
            },
            {
              "ansible-version": "stable-2.15",
              "python-version": "3.13"
            }
          ]